tasks:
  - init: |
      npm install
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      pushd /tmp
      unzip awscliv2.zip
      sudo ./aws/install
      npm install -g aws-cdk@2.132.1
      popd

vscode:
    extensions:
        - graphql.vscode-graphql-syntax